SRC_PREFIX=src/
BIN_PREFIX=bin/
LIBS_PREFIX=.libs/
OBJS_PREFIX=.objs/

CC=gcc

CFLAGS=-g -Wall -Wextra -std=c11 -O3 -I$(SRC_PREFIX)macro/

all: $(BIN_PREFIX)interpreter

LEXER_SRC_PREFIX=$(SRC_PREFIX)lexer/
LEXER_SRC=$(shell find $(LEXER_SRC_PREFIX) -maxdepth 1 -name '*.c')
LEXER_OBJS_PREFIX=$(OBJS_PREFIX)lexer/
LEXER_OBJS=$(patsubst $(LEXER_SRC_PREFIX)%.c,$(LEXER_OBJS_PREFIX)%.o,$(LEXER_SRC))
LEXER_LIB_PREFIX=$(LIBS_PREFIX)lexer/
LEXER_LIB=$(LEXER_LIB_PREFIX)lexer.a

$(LEXER_LIB): $(LEXER_OBJS)
	mkdir -p $(LEXER_LIB_PREFIX)
	ar rcs $@ $^

$(LEXER_OBJS_PREFIX)%.o: $(LEXER_SRC_PREFIX)%.c $(LEXER_SRC_PREFIX)lexer.h $(LEXER_SRC_PREFIX)lexer_priv.h
	mkdir -p $(LEXER_OBJS_PREFIX)
	$(CC) $(CFLAGS) -I$(UTILS_SRC_PREFIX) -c $< -o $@

UTILS_SRC_PREFIX=$(SRC_PREFIX)utils/
UTILS_SRC=$(shell find $(UTILS_SRC_PREFIX) -maxdepth 1 -name '*.c')
UTILS_OBJS_PREFIX=$(OBJS_PREFIX)utils/
UTILS_OBJS=$(patsubst $(UTILS_SRC_PREFIX)%.c,$(UTILS_OBJS_PREFIX)%.o,$(UTILS_SRC))
UTILS_LIB_PREFIX=$(LIBS_PREFIX)utils/
UTILS_LIB=$(UTILS_LIB_PREFIX)utils.a

$(UTILS_LIB): $(UTILS_OBJS)
	mkdir -p $(UTILS_LIB_PREFIX)
	ar rcs $@ $^

$(UTILS_OBJS_PREFIX)%.o: $(UTILS_SRC_PREFIX)%.c $(UTILS_SRC_PREFIX)utils.h
	mkdir -p $(UTILS_OBJS_PREFIX)
	$(CC) $(CFLAGS) -I$(UTILS_SRC_PREFIX) -I$(UTILS_SRC_PREFIX) -c $< -o $@

INTERPETER_SRC_PREFIX=$(SRC_PREFIX)
INTERPETER_SRC=$(shell find $(INTERPETER_SRC_PREFIX) -maxdepth 1 -name '*.c')
INTERPETER_OBJS_PREFIX=$(OBJS_PREFIX)
INTERPETER_OBJS=$(patsubst $(INTERPETER_SRC_PREFIX)%.c,$(INTERPETER_OBJS_PREFIX)%.o,$(INTERPETER_SRC))

$(INTERPETER_OBJS_PREFIX)%.o: $(INTERPETER_SRC_PREFIX)%.c
	mkdir -p $(INTERPETER_OBJS_PREFIX)
	$(CC) $(CFLAGS) -I$(LEXER_SRC_PREFIX) -I$(UTILS_SRC_PREFIX) -c $< -o $@

$(BIN_PREFIX)interpreter: $(INTERPETER_OBJS) $(LEXER_LIB) $(UTILS_LIB)
	mkdir -p $(BIN_PREFIX)
	$(CC) $(CFLAGS) $^ -o $@

.PHONY: clean

clean:
	rm -rf $(BIN_PREFIX) $(OBJS_PREFIX) $(LIBS_PREFIX)
